# BOTTOM IP SHOULD MATCH YOUR COMPUTER, TOP SHOULD MATCH HOST
# USED TO SEND TOPICS TO ROSCORE MASTER ON SEPARATE PC

export ROS_MASTER_URI=http://192.168.1.2:11311
# YOUR COMPUTERS IP BELOW: v
export ROS_IP=192.168.1.2